Allow context cancellation for data transfer workers (#2386)
With this commit, we allow user to kill a running data redistribution task in spqr coordinator console. This feature does not replace existing STOP TASK GROUP support, because this is applicable only for task local to where this SQL is executed. For now, only primary coordinator runs data transfer tasks, but this may change in future. Anyway, STOP TASK GROUP is cluster-wide command, and can be executed from routers (redistribute don't), while KILL TASK is local goroutine cancellation. Ideally, one should use the other, which I leave as a future improvement. 

```
spqr-console=> show task_group_workers;
              worker_id
--------------------------------------
 59181bbc-fe3c-41d2-8c6f-da54f9525aa0
(1 row)

spqr-console=> show task_groups;
            task_group_id             | destination_shard_id |         source_key_range_id          |       destination_key_range_id       | batch_size |             move_task_id             |  state  |
         message            |     created_at      |     updated_at
--------------------------------------+----------------------+--------------------------------------+--------------------------------------+------------+--------------------------------------+---------+--
----------------------------+---------------------+---------------------
 59181bbc-fe3c-41d2-8c6f-da54f9525aa0 | sh2                  | 8b04eab8-043b-4519-afd2-b32e5b3bfbf1 | 940638c4-ce65-4546-a6c2-b631ef3dd495 | 500        | 3dab8c86-e888-4d55-998b-10f0273e3685 | RUNNING | e
xecuted by "localhost:7003" | 25-04-2026 11:50:17 | 25-04-2026 11:50:17
(1 row)

spqr-console=> kill task '59181bbc-fe3c-41d2-8c6f-da54f9525aa0';
                          kill task
-------------------------------------------------------------
 task id -> %!d(string=59181bbc-fe3c-41d2-8c6f-da54f9525aa0)
(1 row)

spqr-console=>

```




```
spqr-console=> REDISTRIBUTE KEY RANGE '8b04eab8-043b-4519-afd2-b32e5b3bfbf1' TO sh2;
ERROR:  failed to await virtual transactions to exit: context canceled
spqr-console=>
```